version: '3'
services: 
  postgres:
    image: postgres:12
    container_name: postgres
    environment: 
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - '${IP}:${POSTGRESQL}'